version: "3.1"
services:
  odoo-web:
    image: odoo:18
    container_name: web-odoo
    depends_on:
      - odoo-db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - odoo-config:/etc/odoo
      - odoo-addons:/mnt/extra-addons
    environment:
      - USER=odoo
      - PASSWORD=odoo
    networks:
      - odoo
  odoo-db:
    image: postgres:latest
    container_name: db-odoo
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo
  pgadmin:
    container_name: pgadmin-odoo
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: amdin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - odoo-pgadmin:/var/lib/pgadmin
    ports:
      - 5433:80
    networks:
      - odoo
    restart: unless-stopped
  odoo-proxy:
    depends_on:
            - odoo-web
    container_name: odoo_proxy
    build:
        context: .
        dockerfile: Dockerfile-nginx
    ports:
        - "8069:8069"
    networks:
      - odoo

networks:
  odoo:
    driver: bridge

volumes:
  odoo-web-data:
  odoo-db-data:
  odoo-config:
  odoo-addons:
  odoo-pgadmin:
